language: node_js

git:
  depth: 5

node_js:
  - "12"

jobs:
  include:
    - stage: "Test"
      script: npm run test
    - stage: "Lint"
      script: npm run lint
    - stage: "Deploy"
      script: "echo "DEPLOY THIS APP!!"

stages:
  - Test
  - Link
  - Deploy
    if: branch = master
