language: node_js

node_js:
  - "12"

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm run test
    - script: npm run lint
      name: "Lint"
    - stage: build
      name: "Build"
      script: npm run build
    - stage: deploy
      script: echo deploy


stages:
  - test
  - build
  - name: deploy
    if: (tag =~ ^v) AND (branch = master)
