language: node_js

node_js:
  - "12"

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm run test
    - script: npm run lint
      name: "Lint"
    - stage: deploy
      script: echo deploy


stages:
  - test
  - name: deploy
    if: branch = master
